MACRO (MSVC_CRT_SECURE_NO_WARNINGS)
    IF (MSVC)
        FOREACH (target ${ARGN})
            SET_TARGET_PROPERTIES (${target} PROPERTIES
                COMPILE_DEFINITIONS _CRT_SECURE_NO_WARNINGS
            )
        ENDFOREACH (target)
    ENDIF (MSVC)
ENDMACRO (MSVC_CRT_SECURE_NO_WARNINGS)

SET(MSVC_FOUND 1)
